### ISSUE TITLE
upon install ... can't get wallet to sync

### ISSUE THREAD

**Issue by kodetronik** [dashhive/wallet.js#20]
i'm running 
system: 
`pop os 20.04` 
dashwallet version:
`v0.2.1`
node version: (installed with webi)
`v18.12.1`
webi version: (shouldn't matter)
`v1.1.15`

anytime i believe `wallet.sync` runs this it has a problem. 
for instance this is the output for 
```
$ dashwallet balances
syncing... (updating info over 5 minutes old)
Fail:
Error: connect ETIMEDOUT ****:***:****:****:***:****
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
```

help command works: 

```
$ dashwallet -h
Usage:
    wallet balances
    wallet export <addr> [./dir/ or ./file.wif]
    wallet friend <handle> [xpub-or-static-addr]
    wallet generate address
    wallet import <./path/to.wif>
    wallet list [--sort wallet,amount,addr] [--json]
    wallet pay <handle|pay-addr> <DASH> [--dry-run] [--coins Xxxxx:xx:0,...]
    wallet remove <addr> [--no-wif]
    wallet stat <addr>
    wallet sync
    wallet version

Global Options:
    --config-dir ~/.config/dash/
    --sync    # wait for sync first

```
and version works: 

```
$ dashwallet version
dashwallet v0.2.1
```

just to show that its installed properly

also things like this don't work either:
```
dashwallet generate address
Fail:
Error: connect ETIMEDOUT ****:*****:****:****:****:****:****:****:***
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
```

when i run this it says i just have no coins

```
$ dashwallet coins

Your wallet is empty. No coins. Sad day. 😢

syncing... (ctrl+c to quit)

```
and then it seems to just error out

**Comment by kodetronik** [comment]
- kodetronik (30/11/2022 17:37) 

8 is lts
[ picture of generate address, sync and list errors ] 
i'm watching the video
i'm not seeing how to start with the wallet
i have a dash core synced locally
i keep getting timed out so i think its not pointing to my wallet address
and its encrypted so i don't know if i need to put a code in

- jojo (30/11/2022 17:40 pm) 

I believe this is meant to be an alternative to Dash Core, not an extension to it. While it may use some Dash SDK Libraries I don't think it is dependent on any of the binaries. @coolaj86 could probably confirm that himself though. 


- kodetronik: (30/11/2022 18:01 pm)

That is super important for me to realize
‘generate address’ is that how I start?

- aj (30/11/2022 18:07 pm)

Everything is ready to go from the moment you run it.
You can friend @whomever to generate an xpub to be shared with someone else or friend @whomever xpubxxxxxx to add their xpub.

Then pay @whomever 0.001 and whatnot.
I will add QR codes to make the xpubs scannable eventually, as well as URLs you can send.


  thread jojo: I believe this is meant to be an alternative to Dash Core...
- aj (30/11/2022 18:13)

Correct, it does not read the DashCore BerkeleyDB files, nor use the RPCs.

It's independent and lightweight (and will hopefully be packagable and distributable with bun).

I would like to add support for reading the BDB files to import existing addresses, but I have to port an existing python parser, otherwise it requires a C-compiler to use. Probably not hard or time consuming, but other stuff is ahead. 

- kodetronik (30/11/2022 18:55)

i'm using v18.2.1
and i haven't got it to work
is there a verbose command?
i can look at the code
@coolaj86
does the timout mean i'm missing a dependency?

- kodetronik (01/12/2022 09:10) 

So this is dashkeys
Does dashkeys have to do with dash wallet?

- aj (01/12/2022 10:20) 

@kodetronik In the beginning there was bitcore and the algorithms were with bitcore and the bitcore was the algorithms and the bitcore and the algorithms and the storage were one.

Then, on the 2^16 day, the bitcore forked into JavaScript and all manner of languages.

Then, on the 2^32 day AJ came along and said "this is stupid, we need small, individually testable code that works in isolation", and so it becomes...

**Comment by coolaj86** [comment]
@kodetronik are you connected to VPN that's been blocked by insight.dash.org?

Or a firewall that blocks outbound https traffic for unauthorized apps?

If you're getting a network timeout, something about your system is misconfigured.

**Comment by coolaj86** [comment]
I think we confirmed later that this was due to an issue with IPv6 not working with insight.dash.org: https://github.com/dashpay/insight-api/issues/95

Workaround: https://dashsight.dashincubator.dev.

Proposed changes for workaround: #32
